"""The specimen catalog.

Each object carries the ground truth the alien needs: facets (what there is to
learn), cue patterns for the offline interpreter, the alien's literal "takes"
when it learns something, and tiered forbidden terms.

A take containing " | " is spoken as separate beats ("Wait." | "...").
"""

from __future__ import annotations

from .models import Combo, Facet, FacetKind, ForbiddenTerm, TargetObject

A, F, M, C = FacetKind.appearance, FacetKind.function, FacetKind.mechanism, FacetKind.context


def f(id, kind, prop, frag, cues, take="", q="", w=1.0, core=False) -> Facet:
    return Facet(
        id=id, kind=kind, property=prop, fragment=frag, cues=cues,
        take=take, question=q, weight=w, core=core,
    )


def names(*terms: str) -> list[ForbiddenTerm]:
    out = []
    for i, t in enumerate(terms):
        # The first name is the object's name: hidden from the forbidden list
        out.append(ForbiddenTerm(term=t, tier="name", visible=i != 0))
    return out


def revealing(*terms: str) -> list[ForbiddenTerm]:
    return [ForbiddenTerm(term=t, tier="revealing") for t in terms]


CATALOG: list[TargetObject] = [
    TargetObject(
        id="toothbrush", name="toothbrush", aliases=["tooth brush", "electric toothbrush"],
        image_url="/objects/s01.svg",
        description="A slim plastic handle with a dense tuft of nylon fibres at one end.",
        function="Cleaning teeth, usually with toothpaste, twice a day.",
        forbidden_terms=names("toothbrush", "tooth brush")
        + revealing("tooth", "teeth", "dental", "dentist", "oral", "bristle", "toothpaste", "brush"),
        conventional_words=["clean", "mouth", "morning", "bathroom", "hygiene", "paste", "plastic", "handle", "germs"],
        related_concepts=["hygiene", "bathroom", "morning routine"],
        difficulty=1, personalization_tags=["wellness", "interiors", "everyday", "philosophy"],
        facets=[
            f("handheld", A, "held in one hand", "a small handheld stick",
              [r"\bhand", r"\bhold", r"\bgrip", r"\bhandle", r"\bstick\b", r"\brod\b", r"\bplastic"],
              "A stick. Humans are very fond of sticks.", "How large is it? Could I hold it?", 0.8),
            f("fibers", A, "has many small flexible fibres", "with a crowd of stiff little hairs at one end",
              [r"\bhair", r"\bfib(er|re)", r"\bthread", r"\bfilament", r"\btuft", r"\bnylon", r"\bspik", r"\bwhisker", r"\bbristl", r"\bfuzz", r"\bsoft (bits|points|spines)"],
              "One end has hair. You built a stick and then gave it hair.", "What is at the end of it?", 1.0, True),
            f("mouth", C, "used inside the mouth", "that goes inside the human face-opening",
              [r"\bmouth", r"\bface\b", r"\blips?\b", r"\bjaw", r"\bgums?\b", r"inside (your|the|my) (head|face)", r"\bbite", r"\bchew", r"\bsmile", r"\bbreath", r"\btongue"],
              "You put it inside your face. Voluntarily.", "Where on the body is it used?", 1.2, True),
            f("clean", F, "cleans something", "to scrub something clean",
              [r"\bclean", r"\bscrub", r"\bpolish", r"\bwash", r"\bscrap(e|ing)", r"\brub", r"\bgerm", r"\bbacteri", r"\bdirt", r"\bfood (stuck|bits|remains)", r"\bhygien", r"\bfresh", r"\bwhite\b", r"\brot\b", r"\bdecay"],
              "So it is a cleaning ritual.", "What does it actually do?", 1.2, True),
            f("paste", M, "used with a flavoured substance", "smeared with a flavoured chemical paste",
              [r"\bpaste", r"\bgel\b", r"\bcream", r"\bmint", r"\bflavou?r", r"\bfoam", r"\bchemical", r"\bsqueez"],
              "And first you coat it in flavoured chemical paste. Of course you do.", "Is anything applied to it?", 0.7),
            f("routine", C, "used daily, like a ritual", "every morning and every night",
              [r"\bmorning", r"\bnight", r"\btwice", r"every (day|night|morning)", r"\bdaily", r"before (bed|sleep)", r"\britual", r"\bhabit", r"\broutine", r"\bsink", r"\bbathroom", r"\bmirror"],
              "Twice a day. So it is a ritual. Humans have many rituals involving the face.", "How often do humans do this?", 0.6),
        ],
        combos=[
            Combo(requires=["mouth", "clean"], line="So humans use a tiny broom to polish the bones inside their faces?"),
            Combo(requires=["fibers", "mouth"], line="You place a hairy stick inside your mouth. I am writing this down."),
        ],
        alien_summary="a tiny broom used to polish the bones inside your face",
    ),
    TargetObject(
        id="umbrella", name="umbrella", aliases=["brolly", "parasol"],
        image_url="/objects/s02.svg",
        description="A collapsible fabric canopy on ribs, held up by a hooked shaft.",
        function="Keeping rain or sun off the person holding it.",
        forbidden_terms=names("umbrella", "brolly") + revealing("parasol"),
        conventional_words=["rain", "wet", "open", "fold", "handle", "weather", "dry"],
        related_concepts=["weather", "rain", "walking"],
        difficulty=1, personalization_tags=["travel", "fashion", "nature", "cities", "melancholy"],
        facets=[
            f("canopy", A, "has a fabric dome", "a portable fabric roof",
              [r"\bfabric", r"\bcloth", r"\bcover", r"\broof", r"\bdome", r"\bcanopy", r"\bsheet", r"\bmaterial", r"\bnylon", r"\bmushroom", r"\bround top", r"\btent"],
              "A roof. But small. And you carry it.", "What shape is it when it is working?", 1.0, True),
            f("handle", A, "held up by a stick", "on a stick",
              [r"\bhandle", r"\bstick", r"\bpole", r"\bshaft", r"\bhook", r"\bcurved", r"\bcane"],
              "Held up by a stick. The stick is doing a lot of work.", "How do you hold it?", 0.7),
            f("folds", M, "opens and folds", "that unfolds and collapses",
              [r"\bopen", r"\bclose", r"\bfold", r"\bcollaps", r"\bexpand", r"\bspring", r"\bbutton", r"\bpop", r"\bshut", r"\bribs?\b", r"\bspokes?"],
              "It changes shape. It hides when it is not needed. A shy object.", "Does it always look like that?", 0.8),
            f("rain", F, "keeps falling water off you", "to keep falling sky-water off your head",
              [r"\brain", r"\bwater", r"\bwet\b", r"\bdrops?\b", r"\bstorm", r"\bweather", r"\bdry\b", r"\bshield", r"\bprotect", r"\bsun\b", r"\bsky\b", r"\bclouds?"],
              "Water falls from your sky and you object to this.", "What does it protect you from?", 1.3, True),
            f("overhead", C, "held above the head", "held above the head while walking",
              [r"\bhead\b", r"\babove", r"over (you|your|my)", r"hold (it )?up", r"\bcarry", r"\bwalk"],
              "You hold it above yourself. A personal cloud, but the opposite.", "Where do you hold it?", 0.7),
            f("forgotten", C, "frequently lost", "and frequently abandoned on public transport",
              [r"\bforget", r"\bforgot", r"\blose\b", r"\blost\b", r"left it", r"\bbad luck", r"\bindoors"],
              "You lose them constantly. So they are migratory.", "", 0.4),
        ],
        combos=[Combo(requires=["canopy", "rain"], line="A portable roof for when your sky leaks.")],
        alien_summary="a portable roof you hold over yourself when the sky leaks",
    ),
    TargetObject(
        id="seatbelt", name="seatbelt", aliases=["seat belt", "safety belt"],
        image_url="/objects/s03.svg",
        description="A woven strap with a metal tongue that clicks into a buckle.",
        function="Restraining a passenger in a vehicle during sudden stops or crashes.",
        forbidden_terms=names("seatbelt", "seat belt", "safety belt") + revealing("belt"),
        conventional_words=["car", "safety", "buckle", "crash", "seat", "click", "driver"],
        related_concepts=["cars", "safety", "travel"],
        difficulty=2, personalization_tags=["cars", "travel", "tech", "robotics"],
        facets=[
            f("strap", A, "a fabric strap across the body", "a fabric strap pulled across the body",
              [r"\bstrap", r"\bband\b", r"\bribbon", r"\bwebbing", r"\bfabric", r"\bstrip", r"\bsash", r"across (your|the|my) (chest|body|lap|shoulder)", r"\bdiagonal"],
              "A ribbon. Worn diagonally. Is it ceremonial?", "What does it look like?", 1.0, True),
            f("vehicle", C, "found in vehicles", "inside moving vehicles",
              [r"\bcars?\b", r"\bvehicle", r"\bdriv", r"\bride", r"\bplanes?\b", r"\bseat", r"\bpassenger", r"\bbus\b", r"\btaxi", r"\bboxes? (that|which) move", r"\bmetal box"],
              "You sit in a fast metal box and then tie yourself to the chair.", "Where is it found?", 1.2, True),
            f("clicks", M, "locks with a click", "that clicks into a lock",
              [r"\bclick", r"\bclip", r"\block", r"\blatch", r"\bbuckle", r"\bsnap", r"\bfasten", r"\binsert", r"metal (tongue|piece|tab)", r"\brelease"],
              "It clicks. Humans find the click reassuring.", "How does it attach?", 0.8),
            f("safety", F, "protects in a sudden stop", "to stop you flying forward when the box stops suddenly",
              [r"\bsafe", r"\bcrash", r"\baccident", r"stops? (suddenly|fast|quickly)", r"\bbrake", r"\bprotect", r"\binjur", r"\bdie\b", r"\bdeath", r"\bhurt", r"fly(ing)? forward", r"\bthrown", r"\bimpact", r"\bsurviv", r"\bcollision"],
              "So your fast boxes sometimes stop very abruptly, and you would keep going without them. This is alarming.", "Why do humans wear it?", 1.3, True),
            f("retract", M, "tightens when yanked", "that tightens when yanked",
              [r"\bretract", r"\btug", r"\bjerk", r"\btight", r"\bslack", r"\broll(s)? (back|up)", r"\bspring", r"locks? when", r"\byank"],
              "It lets you lean slowly but forbids leaning quickly. A strange rule.", "", 0.6),
        ],
        combos=[Combo(requires=["vehicle", "safety"], line="Your vehicles are dangerous enough that you tie yourselves into them. And you keep building them.")],
        alien_summary="a ribbon that ties you to your chair in case your metal box stops suddenly",
    ),
    TargetObject(
        id="zipper", name="zipper", aliases=["zip", "zip fastener"],
        image_url="/objects/s04.svg",
        description="Two rows of interlocking metal or plastic teeth joined by a slider.",
        function="Opening and closing a gap in clothing or bags.",
        forbidden_terms=names("zipper", "zip", "unzip"),
        conventional_words=["jacket", "close", "open", "pull", "clothes", "bag", "teeth"],
        related_concepts=["clothing", "fastening"],
        difficulty=2, personalization_tags=["fashion", "design", "travel", "love"],
        facets=[
            f("teeth", A, "two rows of tiny interlocking teeth", "two rows of tiny interlocking teeth",
              [r"\bteeth", r"\btooth", r"tiny (bumps|ridges|hooks|bits)", r"\binterlock", r"\brows?\b", r"\btrack", r"\bridges?", r"\blinks?\b", r"\bscales", r"\bcoil"],
              "Two rows of tiny teeth. Your clothing has teeth?", "What does it look like up close?", 1.0, True),
            f("slider", M, "a slider runs along it", "joined by a small slider you drag along them",
              [r"\bslid", r"\bpull", r"\btab\b", r"\btag\b", r"\bdrag", r"up and down", r"\bglid", r"\btug"],
              "And a little vehicle runs along the teeth, making them bite each other.", "How does it work?", 1.0, True),
            f("join", F, "joins two edges", "to join two edges of fabric",
              [r"\bjoin", r"\bclos", r"\bopen", r"\bconnect", r"\bfasten", r"\bseal", r"\btogether", r"\bseparat", r"two (sides|edges|halves)", r"\bgap", r"\bshut"],
              "It is a mechanism for making two things become one thing. And then two again.", "What does it do?", 1.2, True),
            f("clothing", C, "on clothes and bags", "on clothing and bags",
              [r"\bjacket", r"\bcoat", r"\bbag", r"\bpants", r"\btrousers", r"\bjeans", r"\bdress", r"\bhoodie", r"\bcloth", r"\bgarment", r"\bpocket", r"\bbackpack", r"\bsuitcase", r"\bwear"],
              "You wear these on your bodies. Some are near the groin. I will not ask.", "Where is it found?", 1.0),
            f("stuck", C, "sometimes jams", "that occasionally refuses to move",
              [r"\bstuck", r"\bjam", r"\bsnag", r"\bbreak", r"\bfly\b", r"\bcatch", r"\bsound", r"\bnoise"],
              "It sometimes refuses to work at the worst possible moment. Like most of your machines.", "", 0.4),
        ],
        combos=[Combo(requires=["teeth", "join"], line="So your coats bite themselves shut.")],
        alien_summary="a tiny vehicle that makes two rows of teeth bite your coat shut",
    ),
    TargetObject(
        id="fork", name="fork", aliases=["dinner fork"],
        image_url="/objects/s05.svg",
        description="A metal handle ending in three or four tines.",
        function="Spearing and lifting food to the mouth.",
        forbidden_terms=names("fork") + revealing("cutlery", "silverware", "utensil", "tines"),
        allowed_lookalikes=["forklift"],
        conventional_words=["eat", "food", "metal", "plate", "knife", "spoon", "dinner"],
        related_concepts=["eating", "table", "cutlery"],
        difficulty=1, personalization_tags=["food", "interiors", "everyday"],
        facets=[
            f("handle", A, "a small metal handle", "a small metal stick",
              [r"\bhandle", r"\bstick", r"\bmetal", r"\bsteel", r"\bsilver", r"\bplastic", r"\bshiny"],
              "A small shiny stick.", "What is it made of?", 0.6),
            f("spikes", A, "ends in several spikes", "that splits into several small spikes",
              [r"\bspik", r"\bpoint", r"\bprong", r"\btips?\b", r"\bteeth", r"\bspear", r"\bsplit", r"\bfour\b", r"\bthree\b", r"\bcomb", r"\bclaw", r"\bsharp", r"\btrident", r"\bfingers"],
              "It ends in several small spikes. So it is a weapon.", "What is at the end?", 1.1, True),
            f("food", F, "used to eat", "used to carry food to the mouth",
              [r"\bfood", r"\beat", r"\bmeal", r"\bdinner", r"\blunch", r"\bbreakfast", r"\bpasta", r"\bnoodle", r"\bsalad", r"\bmeat", r"\bvegetable", r"\bbite", r"\bmouth", r"\bplate"],
              "It is for food. You do not use your hands to eat? Your hands are right there.", "What is it for?", 1.3, True),
            f("stab", M, "spears food", "by stabbing food and lifting it",
              [r"\bstab", r"\bpierc", r"\bpoke", r"\bspear", r"pick (it )?up", r"\blift", r"\bscoop", r"\btwirl", r"\btwist", r"\bskewer", r"\bjab"],
              "You stab your dinner before eating it. To make sure it is defeated?", "How does it hold the food?", 1.0),
            f("table", C, "lives with other table tools", "kept beside a plate",
              [r"\btable", r"\bknife", r"\bspoon", r"\brestaurant", r"\bdrawer", r"\bdish", r"\bmanners", r"left hand", r"\bchopstick"],
              "It has siblings. A cutting one and a scooping one. A family of small weapons.", "", 0.6),
        ],
        combos=[Combo(requires=["spikes", "food"], line="A tiny trident for defeating dinner.")],
        alien_summary="a tiny trident for stabbing your dinner before you eat it",
    ),
    TargetObject(
        id="elevator", name="elevator", aliases=["lift"],
        image_url="/objects/s06.svg",
        description="A small cabin behind sliding metal doors with a panel of numbered buttons.",
        function="Carrying people between floors of a building.",
        forbidden_terms=names("elevator", "lift"),
        conventional_words=["floor", "building", "up", "down", "button", "stairs", "doors"],
        related_concepts=["buildings", "cities", "vertical transport"],
        difficulty=2, personalization_tags=["architecture", "cities", "interiors", "tech", "melancholy", "philosophy"],
        facets=[
            f("box", A, "a small room", "a very small room",
              [r"\bbox", r"\broom", r"\bcabin", r"\bcage", r"\bcompartment", r"\bchamber", r"\bcloset", r"\bcubicle", r"\bpod\b", r"\bcapsule"],
              "A very small room. Is it a prison?", "What does it look like inside?", 1.0, True),
            f("vertical", F, "moves between floors", "that moves up and down between floors",
              [r"\bup\b", r"\bdown\b", r"\bfloors?\b", r"\blevels?\b", r"\bstor(e)?y", r"\bstories", r"\bvertical", r"\brise", r"\bascend", r"\bdescend", r"\bhigher", r"\blower", r"\bupward", r"\bdownward"],
              "The room moves up and down. With you inside it.", "Where does it go?", 1.3, True),
            f("buttons", M, "controlled by numbered buttons", "steered by pressing numbered buttons",
              [r"\bbutton", r"\bpress", r"\bnumbers?\b", r"\bpanel", r"light(s)? up", r"\bding"],
              "You press a number and the room obeys. Dignified.", "How do you control it?", 0.8),
            f("doors", M, "doors slide open", "with sliding doors",
              [r"\bdoors?\b", r"\bslid", r"\bautomatic"],
              "The walls open by themselves. Of course.", "", 0.5),
            f("building", C, "inside tall buildings, instead of stairs", "inside tall buildings so humans need not climb",
              [r"\bbuilding", r"\btower", r"\bskyscraper", r"\bapartment", r"\boffice", r"\bhotel", r"\bmall\b", r"\bstairs?\b", r"\bclimb", r"\bcable", r"\bpulley", r"\bshaft", r"\bmotor"],
              "Your buildings are taller than your patience for stairs.", "Where is it found?", 1.1, True),
            f("awkward", C, "strangers stand in silence", "in which strangers stand silently facing the same wall",
              [r"\bawkward", r"\bsilen", r"\bstranger", r"\bstare", r"\bmusic", r"small talk", r"\bcrowd", r"\bsqueez", r"\bavoid eye"],
              "Strangers stand in a small box and agree not to look at each other. This is the most human thing you have told me.", "", 0.5),
        ],
        combos=[Combo(requires=["box", "vertical"], line="A small room that travels vertically. You built a room that refuses to stay on its floor.")],
        alien_summary="a small room that carries silent strangers vertically",
    ),
    TargetObject(
        id="traffic_light", name="traffic light", aliases=["traffic signal", "stoplight", "stop light"],
        image_url="/objects/s07.svg",
        description="A post-mounted box with red, amber and green lamps.",
        function="Controlling when vehicles and pedestrians may move at junctions.",
        forbidden_terms=names("traffic light", "traffic signal", "stoplight", "stop light") + revealing("traffic"),
        conventional_words=["red", "green", "yellow", "stop", "go", "cars", "road"],
        related_concepts=["roads", "rules", "cities"],
        difficulty=1, personalization_tags=["cities", "cars", "architecture", "robotics", "philosophy"],
        facets=[
            f("lights", A, "three glowing lamps on a pole", "a pole with three glowing eyes",
              [r"\blights?\b", r"\blamps?", r"\bbulb", r"\bglow", r"\bshine", r"\blit\b", r"\bbright", r"three (circles|eyes|lights|lamps)", r"\bpole", r"\bpost\b"],
              "A pole with glowing eyes. Is it alive?", "What does it look like?", 1.0, True),
            f("colors", A, "changes colour", "that change colour",
              [r"\bred\b", r"\bgreen\b", r"\byellow", r"\bamber", r"\borange", r"\bcolou?r"],
              "The colours have meanings? Red is the angry one, I assume.", "Does it change?", 1.0, True),
            f("rules", F, "tells humans when to stop and go", "telling humans when to stop and when to move",
              [r"\bstop", r"\bgo\b", r"\bwait", r"\bslow", r"\brules?\b", r"\bobey", r"\bpermission", r"\ballowed", r"\btells?\b", r"\bsignal", r"\border", r"\binstruct", r"\bcommand", r"\blaw\b"],
              "A light that gives orders. And you obey it? Even when no one is watching?", "What does it do?", 1.3, True),
            f("road", C, "at road crossings", "at places where roads cross",
              [r"\broads?\b", r"\bstreet", r"\bcars?\b", r"\bvehicle", r"\bdriv", r"\bjunction", r"\bintersection", r"\bcrossing", r"\bcorner", r"\bpedestrian", r"\bcross\b"],
              "It stands where roads meet and settles disputes between machines.", "Where does it stand?", 1.1, True),
            f("timer", M, "changes on a schedule", "on a timed cycle",
              [r"\btimer", r"\bcycle", r"\bswitch", r"\bchanges", r"\bevery\b", r"\bminute", r"\bseconds", r"\bautomatic", r"\bsensor", r"\bcamera"],
              "It changes on a schedule. A tiny tyrant with a clock.", "", 0.5),
        ],
        combos=[Combo(requires=["colors", "rules"], line="So the red eye means stop. Humans have agreed to be commanded by colours.")],
        alien_summary="a pole with three coloured eyes that commands your vehicles",
    ),
    TargetObject(
        id="passport", name="passport", aliases=["travel document"],
        image_url="/objects/s08.svg",
        description="A small booklet with a stiff cover, a photo page and pages for stamps.",
        function="Proving identity and nationality when crossing borders.",
        forbidden_terms=names("passport") + revealing("visa", "immigration"),
        conventional_words=["travel", "country", "airport", "identity", "photo", "border", "stamp"],
        related_concepts=["travel", "borders", "identity"],
        difficulty=2, personalization_tags=["travel", "cities", "photography", "words", "philosophy"],
        facets=[
            f("booklet", A, "a small booklet", "a small stiff booklet",
              [r"\bbook", r"\bpages?\b", r"\bnotebook", r"\bcover", r"\bleather", r"\bblue\b", r"\bnavy", r"\bmaroon", r"\bpaper", r"\bdocument"],
              "A very small book. Only one copy exists? Of you?", "What does it look like?", 1.0, True),
            f("identity", F, "proves who you are", "containing a picture of your face and proof of who you are",
              [r"\bphoto", r"\bpicture", r"\bface", r"\bname\b", r"\bidentit", r"who you are", r"\bidentify", r"\bprove", r"\bproof", r"\bbirth", r"\bnationality", r"\bcitizen", r"\bbelong"],
              "It contains a flat copy of your face. So humans do not trust faces. They trust small books about faces.", "What is inside it?", 1.2, True),
            f("borders", F, "grants permission to cross borders", "that grants permission to cross invisible lines between countries",
              [r"\bborder", r"\bcountr", r"\bnation", r"\bcross", r"\babroad", r"\bforeign", r"\binternational", r"\btravel", r"\bairport", r"\benter", r"\bpermission", r"\bflight", r"\bfly\b"],
              "Wait. | Humans carry tiny written records that grant permission to cross invisible geographic boundaries? | Your species is fascinating.", "When do humans use it?", 1.3, True),
            f("stamps", M, "gets stamped by officials", "stamped with ink by officials",
              [r"\bstamp", r"\bink\b", r"\bmarks?\b", r"\bsticker", r"\bscan", r"\bofficer", r"\bofficial", r"\bdesk", r"\bqueue", r"\bchip\b", r"\bbarcode"],
              "Officials strike it with ink. It is a diary written by strangers.", "", 0.7),
            f("government", C, "issued by a government, expires", "issued by a government and expiring after some years",
              [r"\bgovernment", r"\bstate\b", r"\bissued", r"\bexpir", r"\brenew", r"\bvalid", r"\bapply", r"\bapplication"],
              "Your permission to exist abroad expires? Grim.", "", 0.5),
        ],
        combos=[Combo(requires=["identity", "borders"], line="A small book about your face that lets you cross lines nobody can see.")],
        alien_summary="a small book about your face that lets you cross invisible lines",
    ),
    TargetObject(
        id="headphones", name="headphones", aliases=["headphone", "headset", "earphones"],
        image_url="/objects/s09.svg",
        description="Two padded ear cups joined by an arched band.",
        function="Playing sound privately into the wearer's ears.",
        forbidden_terms=names("headphones", "headphone", "earphones", "earphone", "earbuds", "earbud", "headset"),
        conventional_words=["music", "listen", "ears", "sound", "phone", "wireless", "song"],
        related_concepts=["music", "audio", "commuting"],
        difficulty=1, personalization_tags=["music", "tech", "travel", "film", "melancholy", "words"],
        facets=[
            f("ears", A, "worn over the ears", "two cushions clamped over the ears",
              [r"\bears?\b", r"\bhead\b", r"over (your|the|my) (head|ears)", r"both sides", r"\bcushion", r"\bcups?\b", r"\bpads?\b", r"\bband\b", r"\barch"],
              "You clamp two cushions onto your ears. Your ears are cold?", "Where do you wear it?", 1.1, True),
            f("sound", F, "lets you hear sounds", "that pour sound into your head",
              [r"\bsound", r"\bmusic", r"\bsongs?\b", r"\blisten", r"\bhear", r"\baudio", r"\bpodcast", r"\bvolume", r"\bloud", r"\bvoice", r"\bcalls?\b"],
              "It pours sound directly into your head. A private weather.", "What does it do?", 1.3, True),
            f("private", F, "only the wearer hears", "so that no one else hears",
              [r"\bprivate", r"only you", r"nobody else", r"no one else", r"\balone", r"\bisolat", r"\bblock", r"shut out", r"\bcancel", r"\bignore", r"\bpeople around"],
              "Others cannot hear it. So it is a device for being alone in public.", "Who else can hear it?", 0.9),
            f("cable", M, "connects to a device", "connected by wire or invisible signal to a small glowing slab",
              [r"\bwire", r"\bcable", r"\bcord\b", r"\bplug", r"\bbluetooth", r"\bbattery", r"\bcharg", r"\bphone", r"\bdevice", r"\bconnect", r"\btangle"],
              "Connected to your glowing slab. Everything connects to the glowing slab.", "", 0.7),
            f("commute", C, "worn while doing other things", "worn while travelling or working",
              [r"\btrain\b", r"\bbus\b", r"\bcommut", r"\bgym\b", r"\bstudy", r"\bwork", r"\bfocus", r"\bstreet", r"\bwalk"],
              "You wear it while doing other things. You are never fully in one place.", "", 0.5),
        ],
        combos=[Combo(requires=["ears", "sound"], line="A machine that whispers into both sides of your head at once.")],
        alien_summary="two cushions that whisper into your head so nobody else can hear",
    ),
    TargetObject(
        id="shopping_cart", name="shopping cart", aliases=["cart", "trolley", "shopping trolley"],
        image_url="/objects/s10.svg",
        description="A wheeled wire basket with a push handle.",
        function="Carrying items around a shop before paying.",
        forbidden_terms=names("shopping cart", "cart", "trolley", "shopping trolley"),
        conventional_words=["supermarket", "groceries", "push", "wheels", "store", "buy", "food"],
        related_concepts=["shopping", "groceries"],
        difficulty=1, personalization_tags=["food", "cities", "everyday"],
        facets=[
            f("basket", A, "a wire basket", "a wire cage",
              [r"\bbasket", r"\bcage", r"metal (frame|box|mesh)", r"\bwire", r"\bgrid", r"\bbox\b", r"\bcontainer", r"\bmesh", r"\bbars\b"],
              "A cage. For what animal?", "What does it look like?", 1.0, True),
            f("wheels", M, "on wheels, pushed", "on squeaky wheels, pushed from behind",
              [r"\bwheel", r"\broll", r"\bpush", r"\bsteer", r"\bhandle", r"\bwobbl", r"\bsqueak"],
              "The cage has wheels and you push it. So the animal does not walk.", "How does it move?", 1.0, True),
            f("carry", F, "carries things you will buy", "that you fill with things you intend to buy",
              [r"\bcarry", r"\bload", r"\bfill", r"\bitems", r"\bthings", r"\bstuff", r"\bgoods", r"\bbuy", r"\bpurchas", r"\bproducts", r"\bgrocer", r"\bfood"],
              "You fill the cage with objects you have not paid for yet. Then you pay. Then you abandon the cage. A ritual of temporary ownership.", "What goes in it?", 1.2, True),
            f("store", C, "used inside shops", "inside large food buildings",
              [r"\bshop", r"\bstore", r"\bmarket", r"\baisle", r"\bcheckout", r"\bcashier", r"\btill\b", r"\bparking", r"\bmall\b"],
              "Inside the food building. Humans gather food by pushing cages down long corridors.", "Where is it used?", 1.1, True),
            f("nest", C, "they stack inside each other", "that nest inside one another",
              [r"\breturn", r"\bcoin", r"\bchain", r"\bstack", r"\bnest", r"\babandon", r"\blot\b"],
              "They stack inside each other. Nesting cages.", "", 0.4),
        ],
        combos=[Combo(requires=["basket", "wheels"], line="A cage with wheels. You push it ahead of you like a small obedient animal.")],
        alien_summary="a wheeled cage you push through food corridors to collect things you have not paid for",
    ),
    TargetObject(
        id="doorbell", name="doorbell", aliases=["door bell"],
        image_url="/objects/s11.svg",
        description="A small button mounted by a front door.",
        function="Letting a visitor announce themselves by making a chime inside.",
        forbidden_terms=names("doorbell", "door bell") + revealing("bell"),
        conventional_words=["door", "ring", "visitor", "button", "house", "press", "sound"],
        related_concepts=["home", "visitors"],
        difficulty=2, personalization_tags=["architecture", "interiors", "tech", "love"],
        facets=[
            f("button", A, "a button on the wall", "a small button beside the entrance",
              [r"\bbutton", r"\bpress", r"\bpush", r"small (box|switch)", r"\bswitch", r"\bplastic", r"\bwall\b", r"\bglow"],
              "A button on the outside of your dwelling. Anyone may press it?", "What does it look like?", 1.0, True),
            f("sound", F, "makes a sound inside", "that makes a sound inside the house",
              [r"\bsound", r"\brings?\b", r"\bding", r"\bdong", r"\bchime", r"\bbuzz", r"\bnoise", r"\bmusic", r"\bbeep", r"\btone", r"\bmelody"],
              "Pressing it outside makes noise inside. It is a nerve for your house.", "What happens when you press it?", 1.2, True),
            f("visitor", F, "announces visitors", "to announce that someone has arrived",
              [r"\bvisit", r"\bguest", r"\bsomeone", r"\bfriend", r"\bstranger", r"\bdeliver", r"\bcourier", r"\bneighbou?r", r"\barriv", r"\bknock", r"\bpeople"],
              "So a visitor presses it instead of simply entering. Polite. Also suspicious.", "Who uses it?", 1.2, True),
            f("house", C, "at the entrance of homes", "at the entrance to a dwelling",
              [r"\bdoors?\b", r"\bhouse", r"\bhome", r"\bapartment", r"\bflat\b", r"\bfront\b", r"\bentrance", r"\boutside", r"\bporch", r"\bgate"],
              "It lives at the edge of your dwelling.", "Where is it?", 1.0),
            f("camera", M, "some have cameras", "some now with a little eye that watches",
              [r"\bcamera", r"\bvideo", r"\bapp\b", r"\bsmart", r"\bwireless", r"\bsee who"],
              "Some of them have eyes now. Your houses watch your visitors.", "", 0.4),
        ],
        combos=[Combo(requires=["visitor", "sound"], line="A visitor pushes a button and your house screams politely.")],
        alien_summary="a button that makes your house scream politely when a visitor arrives",
    ),
    TargetObject(
        id="remote_control", name="remote control", aliases=["remote", "clicker", "tv remote"],
        image_url="/objects/s12.svg",
        description="A small handheld rectangle covered in rubber buttons.",
        function="Operating a television or other device from a distance.",
        forbidden_terms=names("remote control", "remote", "clicker", "controller"),
        conventional_words=["tv", "buttons", "channel", "couch", "batteries", "volume", "change"],
        related_concepts=["television", "living room"],
        difficulty=1, personalization_tags=["tech", "interiors", "film", "robotics", "melancholy"],
        facets=[
            f("shape", A, "a small rectangle", "a small slab",
              [r"\brectang", r"\bslab", r"\bstick\b", r"\bbar\b", r"\bplastic", r"\bblack\b", r"\bhandheld", r"\bhold", r"\bhand\b"],
              "A slab. Humans like slabs.", "What does it look like?", 0.7),
            f("buttons", M, "covered in buttons", "covered in buttons, one for each wish",
              [r"\bbuttons?", r"\bpress", r"\bclick", r"\bnumbers?", r"\barrows?", r"\bvolume", r"\bpower", r"\bmute", r"\bchannel"],
              "Covered in buttons. Each button is a different wish.", "How do you use it?", 1.0, True),
            f("distance", F, "controls things from a distance", "that commands machines across the room without touching them",
              [r"\bdistance", r"\bfar\b", r"\bacross", r"from (the|your|my) (couch|sofa|bed|chair)", r"without (getting up|moving|touching|walking)", r"\bwireless", r"\binvisible", r"\bbeam", r"\binfrared", r"\bpoint", r"\baim"],
              "You command the machine from across the room. Without touching it. Telekinesis with extra steps.", "What does it do?", 1.3, True),
            f("tv", C, "used with the big glowing screen", "aimed at the big glowing screen",
              [r"\btv\b", r"\btelevision", r"\bscreen", r"\bshows?\b", r"\bchannel", r"\bfilm", r"\bmovie", r"\bwatch", r"\bstream", r"\bair condition", r"\bfan\b"],
              "It is for the big glowing screen. So the screen also obeys.", "What does it control?", 1.1, True),
            f("couch", C, "lives in the couch", "and frequently lost between cushions",
              [r"\bcouch", r"\bsofa", r"\blazy", r"\blying", r"\bbed\b", r"\blost", r"\bcushion", r"\bmissing", r"\bbatter"],
              "And it hides in the cushions. A creature of the couch.", "", 0.5),
        ],
        combos=[Combo(requires=["distance", "tv"], line="So humans built a glowing wall of stories and then a wand to command it from the couch.")],
        alien_summary="a wand of buttons for commanding the glowing screen without leaving the couch",
    ),
    TargetObject(
        id="telescope", name="telescope", aliases=["scope"],
        image_url="/objects/s13.svg",
        description="A long tube with an eyepiece, standing on a tripod.",
        function="Making distant objects, especially in the sky, appear closer.",
        forbidden_terms=names("telescope") + revealing("scope", "astronomy", "astronomer"),
        conventional_words=["stars", "sky", "lens", "space", "planets", "night", "zoom"],
        related_concepts=["astronomy", "space", "optics"],
        difficulty=2, personalization_tags=["space", "photography", "nature", "tech", "philosophy"],
        facets=[
            f("tube", A, "a long tube on legs", "a long tube standing on three legs",
              [r"\btubes?\b", r"\bcylinder", r"\bpipe", r"\bbarrel", r"\blong\b", r"\btripod", r"\bstand\b", r"\blegs"],
              "A long tube on three legs. A tall insect?", "What does it look like?", 1.0, True),
            f("lens", M, "you look through it with one eye", "that you look through with one eye",
              [r"\blens", r"\bglass", r"\bmirror", r"\bcurved", r"\beyepiece", r"look (through|into)", r"\bpeer", r"one eye", r"\bsquint"],
              "You look into it with one eye and close the other. Why close the other?", "How do you use it?", 0.9),
            f("magnify", F, "makes distant things look close", "that makes faraway things look near",
              [r"\bfar\b", r"\bdistant", r"\bcloser", r"\bbigger", r"\bmagnif", r"\bzoom", r"\benlarge", r"\bdetail", r"look (at|closer)", r"\baway\b"],
              "It pulls distant things closer without moving them. A lie made of glass. A useful lie.", "What does it do?", 1.3, True),
            f("sky", C, "pointed at the night sky", "pointed up at the night sky",
              [r"\bsky", r"\bstars?\b", r"\bplanets?", r"\bmoon", r"\bnight", r"\bspace\b", r"\bgalax", r"\buniverse", r"\bsaturn", r"\bmars\b", r"\bcomet", r"\bheaven"],
              "You point it at the sky. You are looking for things like me.", "What do humans look at with it?", 1.2, True),
            f("patience", C, "used for hours in the cold", "for hours, in the cold, patiently",
              [r"\bwait", r"\bhours", r"\bpatien", r"\bquiet", r"\bhill", r"\broof", r"\bbackyard", r"\bfocus", r"\bknob", r"\badjust", r"\bcold\b"],
              "You wait in the cold for hours to look at a dot. I respect this.", "", 0.5),
        ],
        combos=[Combo(requires=["magnify", "sky"], line="Humans built a tube for staring at other worlds. | Wait. | Have you been staring at mine?")],
        alien_summary="a tube on legs for staring at other worlds, possibly mine",
    ),
    TargetObject(
        id="satellite_dish", name="satellite dish", aliases=["dish", "dish antenna"],
        image_url="/objects/s14.svg",
        description="A shallow curved metal bowl with a receiver arm, bolted to a wall.",
        function="Receiving broadcast signals from orbiting satellites.",
        forbidden_terms=names("satellite dish", "dish") + revealing("satellite", "antenna", "antennae"),
        conventional_words=["tv", "signal", "roof", "channels", "space", "receive"],
        related_concepts=["broadcast", "orbit", "television"],
        difficulty=3, personalization_tags=["space", "tech", "architecture", "robotics"],
        facets=[
            f("bowl", A, "a large curved bowl", "a large curved bowl",
              [r"\bbowl", r"\bplate", r"\bsaucer", r"\bcurve", r"\bround", r"\bcircle", r"\bconcave", r"\bdis[ck]\b", r"\bmetal", r"\bumbrella"],
              "A giant bowl. For giant soup?", "What shape is it?", 1.0, True),
            f("mounted", C, "attached to buildings", "fixed to the outside of buildings",
              [r"\broof", r"\bwall\b", r"\bbalcon", r"\bhouse", r"\bbuilding", r"\boutside", r"\bpole", r"\bmounted", r"\battached", r"\bbolted"],
              "You attach bowls to your houses. Facing upward. Waiting.", "Where is it?", 0.9),
            f("signal", F, "catches invisible signals", "that catches invisible messages falling from the sky",
              [r"\bsignal", r"\bwaves?\b", r"\btransmi", r"\bbroadcast", r"\breceiv", r"\bcatch", r"\bcollect", r"\bdata", r"\binformation", r"\bmessage", r"\binvisible", r"\bradio", r"\bbeam"],
              "It catches invisible messages. From above. I am now very interested.", "What does it do?", 1.4, True),
            f("tv", C, "used for television", "so your glowing screens have something to show",
              [r"\btv\b", r"\btelevision", r"\bchannels?", r"\bshows", r"\binternet", r"\bnews", r"\bsports", r"\bcable"],
              "And you use these messages to watch other humans chasing a ball? Fine.", "What do humans use it for?", 0.9),
            f("aimed", M, "aimed at a precise spot in the sky", "aimed at a precise spot in the sky",
              [r"\bpoint", r"\baim", r"\bangle", r"\bdirection", r"\btilt", r"\bsouth", r"\bsky\b", r"\borbit", r"\bspace\b", r"machine(s)? (in|up)", r"\babove", r"\bexact"],
              "It must face one exact spot in the sky. Something is up there, talking to you.", "Which way does it face?", 1.0, True),
        ],
        combos=[Combo(requires=["bowl", "signal"], line="A bowl for catching invisible messages. I have one of these. Mine is better.")],
        alien_summary="a giant bowl bolted to your house to catch invisible messages from the sky",
    ),
    TargetObject(
        id="screwdriver", name="screwdriver", aliases=["screw driver"],
        image_url="/objects/s15.svg",
        description="A chunky handle with a long steel shaft and a shaped tip.",
        function="Turning screws to fasten or loosen them.",
        forbidden_terms=names("screwdriver", "screw driver") + revealing("screw", "phillips", "flathead"),
        conventional_words=["tool", "turn", "tighten", "metal", "fix", "handle", "twist"],
        related_concepts=["tools", "repair", "assembly"],
        difficulty=2, personalization_tags=["robotics", "diy", "tech", "interiors"],
        facets=[
            f("handle", A, "a handle with a metal shaft", "a fat handle with a thin metal shaft",
              [r"\bhandle", r"\bgrip", r"\bhold", r"\bplastic", r"\brubber", r"\bwood", r"\bstick", r"\brod\b", r"\bshaft", r"\bmetal", r"\bthin\b"],
              "A handle with a metal needle. A tool. Or a very small spear.", "What does it look like?", 0.9, True),
            f("tip", A, "a shaped tip that fits a groove", "whose tip fits into a matching groove",
              [r"\btip\b", r"\bflat\b", r"\bcross\b", r"\bstar\b", r"\bplus\b", r"\bfits?\b", r"\bslot", r"\bgroove", r"\bblade", r"\bhead\b"],
              "The tip has a specific shape. So it is a key. A key for... what?", "What is special about the end?", 0.9),
            f("twist", M, "turned by twisting the wrist", "that you twist with the wrist",
              [r"\btwist", r"\bturn", r"\brotat", r"\bspin", r"\bclockwise", r"\bwrist", r"\bwind\b"],
              "You twist it. So humans fix things by rotating them.", "How do you use it?", 1.1, True),
            f("fasten", F, "drives small metal spirals that hold things together", "to drive small metal spirals that hold things together",
              [r"\btighten", r"\bloosen", r"\bfasten", r"\battach", r"hold(s)? (things )?together", r"\bjoin", r"\bsecure", r"\bassembl", r"take (it|things) apart", r"\bfix", r"\brepair", r"\bbuild", r"\bfurniture", r"\bbolt", r"\bpins?\b", r"\bspiral", r"\bthread"],
              "Your furniture is held together by tiny metal spirals. And this is the only key.", "What is it for?", 1.3, True),
            f("toolbox", C, "lives in a toolbox", "kept in a box of other tools",
              [r"\btoolbox", r"\btools", r"\bdrawer", r"\bgarage", r"\bworkshop", r"\bdiy\b", r"\bikea", r"\belectronics", r"\bkit\b"],
              "It lives in a box with its siblings. A drawer of very small solutions.", "", 0.5),
        ],
        combos=[Combo(requires=["twist", "fasten"], line="You twist tiny metal spirals into wood until the wood agrees to be a chair.")],
        alien_summary="a twistable key for tiny metal spirals that hold your furniture together",
    ),
    TargetObject(
        id="vending_machine", name="vending machine", aliases=["snack machine", "drinks machine"],
        image_url="/objects/s16.svg",
        description="A tall glass-fronted cabinet of snacks on spiral coils, with a keypad and coin slot.",
        function="Selling snacks and drinks automatically.",
        forbidden_terms=names("vending machine", "vending", "vendor"),
        conventional_words=["snacks", "money", "coins", "buy", "drinks", "button", "machine"],
        related_concepts=["snacks", "automation", "convenience"],
        difficulty=2, personalization_tags=["food", "cities", "tech", "robotics"],
        facets=[
            f("box", A, "a tall glowing box with things behind glass", "a tall glowing box with food displayed behind glass",
              [r"\bbox", r"\bmachine", r"\bcabinet", r"\btall\b", r"\bglass", r"\bwindow", r"\brows", r"\bshelves", r"\bcoils?", r"\blit\b", r"\bglow"],
              "A tall glowing box displaying food behind glass. A museum of snacks.", "What does it look like?", 1.0, True),
            f("pay", M, "takes money", "that accepts money",
              [r"\bcoins?", r"\bmoney", r"\bpay", r"\bcash", r"\bcard\b", r"\btap\b", r"\binsert", r"\bslot", r"\bchange\b", r"\bprice", r"\bcost", r"\bbuy"],
              "You feed it money first. It must be fed before it feeds you.", "What does it want from humans?", 1.1, True),
            f("choose", M, "you choose by pressing a code", "where you type a code for what you want",
              [r"\bchoose", r"\bselect", r"\bbutton", r"\bcode\b", r"\bletter", r"\bkeypad", r"\bpress", r"\bpick\b"],
              "You speak to it in numbers. It understands only numbers.", "How do you tell it what you want?", 0.7),
            f("drops", F, "drops your choice to the bottom", "that drops your choice into a slot at the bottom",
              [r"\bdrops?\b", r"\bfalls?\b", r"\brelease", r"\bdispens", r"\bspits?", r"push(es)? out", r"\btray", r"\bbottom", r"\bflap", r"\bgrab", r"\bspiral", r"\bspin"],
              "Then it pushes the food off a ledge. Violence, but organised.", "How do you get the food?", 1.2, True),
            f("snacks", C, "sells snacks and drinks", "selling small snacks and drinks",
              [r"\bsnack", r"\bdrinks?", r"\bsoda", r"\bchips", r"\bcrisps", r"\bchocolate", r"\bcandy", r"\bfood", r"\bwater", r"\bbottle", r"\bcans?\b", r"\bsweets", r"\bcoffee"],
              "Snacks. Small, unnecessary foods. Your species loves them.", "What is inside?", 1.1, True),
            f("stuck", C, "sometimes keeps your snack", "and occasionally keeps both the money and the snack",
              [r"\bstuck", r"\bshake", r"\bhit\b", r"\bkick", r"\btilt", r"\bjam", r"\bhang", r"\bsteal", r"eats? (my|your) money"],
              "Sometimes it keeps the food and the money. And then you strike it. Humans negotiate by force.", "", 0.4),
        ],
        combos=[Combo(requires=["pay", "drops"], line="A box that takes your money and then throws food off a shelf at you. You call this convenience.")],
        alien_summary="a glowing box that eats your money and throws snacks off a shelf",
    ),
]

BY_ID: dict[str, TargetObject] = {o.id: o for o in CATALOG}


def get(object_id: str) -> TargetObject:
    return BY_ID[object_id].model_copy(deep=True)
